# Generated by Django 4.2.6 on 2023-12-07 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(through='courses.CourseMembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
