# Generated by Django 4.2.6 on 2023-12-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_length_hours_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='length_hours',
            new_name='course_length_hours',
        ),
    ]
